sudo: required
language: python
services:
  - docker

python:
  - "3.6"
env:
  DJANGO_CONFIGURATION=local
  API_BASE=http://0.0.0.0:8000
  # API_BASE=http://localhost:8000
  SECRET_KEY=cgasj6yjpkagcgasj6yjpkagcgasj6yjpkag
  DEFAULT_PASSWORD=pkdb

  DB_NAME=postgres
  DB_PASSWORD=postgres
  DB_SERVICE=postgres
  DB_USER=postgres
  DB_URL=localhost
  DB_PORT=5432

  EMAIL_HOST_USER=
  EMAIL_HOST_PASSWORD=

before_script:
  - docker-compose build


script:
  - docker-compose run --rm backend bash -c "./manage.py test"

notifications:
  email: false

cache:
  pip: true

