sudo: required
language: python
services:
  - docker

python:
  - "3.6"
env:
  PKDB_DOCKER_COMPOSE_YAML=docker-compose-develop.yml
  PKDB_DJANGO_CONFIGURATION=local

  PKDB_API_BASE="http://0.0.0.0:8000"

  PKDB_SECRET_KEY="cgasj6yjpkagcgasj6yjpkagcgasj6yjpkag"
  PKDB_DEFAULT_PASSWORD="pkdb"

  PKDB_DB_NAME=postgres
  PKDB_DB_PASSWORD=postgres
  PKDB_DB_SERVICE=postgres
  PKDB_DB_USER=postgres
  PKDB_DB_URL=localhost
  PKDB_DB_PORT=5432

  PKDB_EMAIL_HOST_USER=
  PKDB_EMAIL_HOST_PASSWORD=


before_script:
  - ./docker-purge.sh

script:
  -docker-compose -f $PKDB_DOCKER_COMPOSE_YAML run --rm backend bash -c "/usr/local/bin/python manage.py test pkdb_app.tests"

notifications:
  email: false

cache:
  pip: true

