version: '2'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:10.5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: pass

  web:
    restart: always
    environment:
      PKDB_SECRET_KEY: cgasj6yjpkagcgasj6yjpkagcgasj6yjpkag
      PKDB_API_BASE: http://0.0.0.0:8000
      PKDB_DEFAULT_PASSWORD: pkdb
      PKDB_EMAIL_HOST_USER: ""
      PKDB_EMAIL_HOST_PASSWORD: ""
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py makemigrations &&
               ./manage.py migrate &&
               ./manage.py createsuperuser2 --username admin --password pkdb --email koenigmx@hu-berlin.de --noinput &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch

  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - postgres_data:/usr/share/elasticsearch/data


#  documentation:
#    restart: always
#    build: ./
#    command: "mkdocs serve"
#    volumes:
#      - ./:/code
#    ports:
#      - "8001:8001"
