#########################################################
# PKDB
#########################################################
#   docker-compose up -d
#########################################################
version: '3'

volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  django_app:
    driver: local
  django_static:
    driver: local

services:
  web:
    restart: always
    build: ./web
    volumes:
      - ./web:/usr/src/app
      - django_app:/usr/src/app
      - django_static:/usr/src/app/static
    env_file: .env.local
    expose: 
      - "8000"
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
     - postgres
     - elasticsearch
    command: bash -c "/usr/local/bin/python /usr/src/app/manage.py collectstatic --noinput && /usr/local/bin/gunicorn pkdb_app.wsgi:application -w 4 -b :8000"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "1234:80"
    volumes:
      - /www/static
      - django_app:/usr/src/app
      - django_static:/usr/src/app/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:10.5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    restart: always
    image: elasticsearch:6.4.2
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data