# -----------------------------------------------------------------------------
# PK-DB docker deploy
# -----------------------------------------------------------------------------
# set environment variables on server:
#     cp /var/git/pkdb/.env.local /var/git/pkdb/.env
#
# rebuild containers:
#     docker-compose -f docker-compose-deploy.yml up --detach
#
# start containers:
#     docker-compose -f docker-compose-deploy.yml up --detach
#
# FIXME: remove migrations and setup root from docker
# FIXME: handle initial indices better
# -----------------------------------------------------------------------------
version: '3'

volumes:
  django_static:
    driver: local
  django_media:
    driver: local
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  vue_dist:
    driver: local
  node_modules:
    driver: local
    
services:
  backend:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/code
      - django_static:/static
      - django_media:/media
    env_file: .env.local
    expose:
      - "8000"
      - "25"
    ports:
      - "8000:8000"
      - "25:25"
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch
    depends_on:
     - postgres
     - elasticsearch
    command: bash -c "/usr/local/bin/gunicorn pkdb_app.wsgi:application --log-config gunicorn_logging.conf -w 4 --bind 0.0.0.0:8000"

  migration:
    build: ./backend
    command: bash -c "/usr/local/bin/python manage.py makemigrations && /usr/local/bin/python manage.py migrate && /usr/local/bin/python manage.py collectstatic --noinput "
    env_file: .env.local
    volumes:
      - ./backend:/code
      - django_static:/static
      - django_media:/media
    links:
      - postgres:postgres
    depends_on:
      - postgres
      - backend

  setup_root:
    build: ./backend
    command: bash -c "/usr/local/bin/python manage.py createsuperuser2 --username admin --password ${DEFAULT_PASSWORD} --email koenigmx@hu-berlin.de --noinput"
    env_file: .env.local
    volumes:
      - ./backend:/code
      - django_static:/static
      - django_media:/media
    depends_on:
      - postgres
      - backend
      - migration

  postgres:
    restart: always
    image: postgres:11.1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    restart: always
    image: elasticsearch:6.4.2
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 1234:80
    volumes:
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - django_static:/static
      - django_media:/media
      - vue_dist:/usr/share/nginx/vuehtml
    depends_on:
      - backend
      - frontend
    links:
      - backend:backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-deploy
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules/
      - vue_dist:/usr/share/nginx/vuehtml
